[package]
name = "cassiopeia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firebase-rs = "2.0.6"
serde = "1.0.160"
serde_json = "1.0.96"
tokio = { version =  "1.28.0", features = ["full"] }
